nav:
  Home: /
  About: /about/
  Blog: /archives/
  Projects: https://github.com/richja
  Hire me: "mailto:hello@richja.cz"

projects_url: https://github.com/richja

customize:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/avatar.png
        favicon: /images/favicon.png # path to favicon
    social_links:
        github: https://github.com/richja
        twitter: https://twitter.com/irql
        delicious: https://del.icio.us/richja
        # facebook: /
        linkedin: https://linkedin.com/in/richjan
    post_count: 10
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
